project_id = "hpzfmcdmywofxioayiff"

[functions.compress-3d-model]
verify_jwt = true

[functions.generate-proposal-pdf]
verify_jwt = true

[functions.generate-maintenance-report-pdf]
verify_jwt = true

[functions.generate-proposal-pdf-public]
verify_jwt = false

[functions.admin-manage-users]
verify_jwt = true

[functions.admin-openai-key]
verify_jwt = true
